apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: nginx/chart
      sourceRef:
        kind: GitRepository
        name: pctl-profile-nginx-profile-main
        namespace: default
  interval: 0s
status: {}
