apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: pctl-profile-nginx-nginx-deployment
  namespace: default
spec:
  interval: 5m0s
  path: nginx/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: pctl-profile-nginx-profile-main
    namespace: default
  targetNamespace: default
status: {}
